import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
export default function Home() {
  return (
    <div className={styles.container}>
      <style jsx >
        {`
          .heading {
            font-size: 45px;
          }
        `}
      </style>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          <span className='myspan'>W</span>
          elcome to CoderHub
        </h1>
        <Image  src="/intro.jpg" width={237} height={150}  className={styles.myimg} />
        <p className={styles.description}>
          Hunting for bugs right here are they 
        </p>

      <div className="blogs">
        <h1 className='heading'>Popular blogs</h1>
        <div className={styles.blogitem}>
          <h2>How to learn javascript in 2022</h2>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Tenetur, animi! Doloribus, architecto.</p>
        </div>
        <div className={styles.blogitem}>
          <h2>How to learn javascript in 2022</h2>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Tenetur, animi! Doloribus, architecto.</p>
        </div>
        <div className={styles.blogitem}>
          <h2>How to learn javascript in 2022</h2>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Tenetur, animi! Doloribus, architecto.</p>
        </div>
        <div className={styles.blogitem}>
          <h2>How to learn javascript in 2022</h2>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Tenetur, animi! Doloribus, architecto.</p>
        </div>
      </div>
      </main>
    </div>
  )
}
